/*
 * Info.java
 *
 * Created on 7. Februar 2008, 14:23
 */
package simulator;

import java.util.ResourceBundle;

/**
 *
 * @author Diego
 */
public class About extends javax.swing.JInternalFrame {

    /**
     * Creates new form Info
     */
    public About() {
        initComponents();
        translate();
    }
    
    /**
     * Translate the Frame texts
     */
    public final void translate() {
        ResourceBundle bundle = Config.getInstance().getBundle();

        this.setTitle(bundle.getString("About.title"));
        jbExit.setText(bundle.getString("About.jbExit.text"));
        jtpInformation.setText(bundle.getString("About.jtpInformation.text"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtpInformation = new javax.swing.JTextPane();
        jbExit = new javax.swing.JButton();

        setTitle("Sobre");

        jtpInformation.setEditable(false);
        jtpInformation.setBackground(new java.awt.Color(224, 223, 227));
        jtpInformation.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jtpInformation.setText("Versão 1.0 Beta\nAutor Diego Müller\n\nVersão 2.0 Beta\nAutor Cristiano Führ Poletti\n\nEste produto é OPEN SOURCE");
        jScrollPane1.setViewportView(jtpInformation);

        jbExit.setText("Sair");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(333, Short.MAX_VALUE)
                        .addComponent(jbExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExit)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbExitActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbExit;
    private javax.swing.JTextPane jtpInformation;
    // End of variables declaration//GEN-END:variables
}
